import pytest

from profile_generator import sanitize_model_output


@pytest.mark.parametrize(
    "input_text,expected",
    [
        (
            "Here is the LinkedIn outreach message: Hi Girish, I noticed your work... (Note: generated by AI)",
            "Hi Girish, I noticed your work...",
        ),
        (
            "Here's the generated LinkedIn outreach message - Hi Jane, great work on product launches.",
            "Hi Jane, great work on product launches.",
        ),
        ("outputted LinkedIn outreach message: Hi Mani, I noticed...", "Hi Mani, I noticed..."),
        ("output: Hi Ben, I noticed...", "Hi Ben, I noticed..."),
        (
            "Assistant: Hi Sam — I liked your profile. [Generated by AI]",
            "Hi Sam — I liked your profile.",
        ),
        (
            "a LinkedIn outreach message based on the provided context: Hi Ritesh, ...",
            "Hi Ritesh, ...",
        ),
        ("\n\n\"Hi Quoted\"\n", "Hi Quoted"),
        ("", ""),
    ],
)
def test_sanitize_variants(input_text, expected):
    out = sanitize_model_output(input_text)
    assert out == expected
